### PR TITLE
Hacking

### PR DESCRIPTION
**Pull request by daniel-thompson**
Just a couple of small bug fixes:
1. Get it building on libftdi-1.2 (i.e. latest Fedora). I'm hardly a cmake expert but nevertheless the changes look sane to me (tm).
2. Make --long behave like it says in --help.

### CODE REVIEW

**Comment by daniel-thompson** [comment]
Rather belated... but ping?

@sdrobertw : Any clue who has write access to this project?

**Comment by mattyclarkson** [comment]
This works for me on Arch Linux. Thanks for this.

Would be useful if this was upstreamed...

**Comment by daniel-thompson** [comment]
@96boards/website-team : Any idea who owns this repo and can accept PRs?

**Comment by pcolmer** [comment]
@daniel-thompson The only person is @glikely

**Comment by pcolmer** [comment]
@daniel-thompson There isn't anyone as the repo owner.

@glikely is recorded as an external contributor with write access but nobody is listed as having ownership.

**Comment by daniel-thompson** [comment]
Is there any way to move this over to someone from the 96Boards team (@ric96 maybe)?

**Comment by glikely** [comment]
Haven't looked at that repo in a very long time. I've merged the PR.
Apparently I still have the rights to do that.

g.

**Comment by daniel-thompson** [comment]
Thanks Grant!

**Pull request merged**
